export type Seeds = import("./src/wdk-manager.js").Seeds;
export type WdkConfig = import("./src/wdk-manager.js").WdkConfig;
export type TransferOptions = import("./src/wdk-manager.js").TransferOptions;
export type TransferResult = import("./src/wdk-manager.js").TransferResult;
export type SwapOptions = import("./src/wdk-manager.js").SwapOptions;
export type SwapResult = import("./src/wdk-manager.js").SwapResult;
export type BridgeOptions = import("./src/wdk-manager.js").BridgeOptions;
export type BridgeResult = import("./src/wdk-manager.js").BridgeResult;
export type IWalletAccount = import("./src/wallet-account.js").default;
export { default, Blockchain } from "./src/wdk-manager.js";
