name: build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: "npm"
      - name: Configure Git to use PAT for GitHub
        run: |
          # cover 'git@github.com:org/repo.git'
          git config --global url."https://x-access-token:${{ secrets.PAT }}@github.com/".insteadOf "git@github.com:"
          # cover 'ssh://git@github.com/org/repo.git'
          git config --global url."https://x-access-token:${{ secrets.PAT }}@github.com/".insteadOf "ssh://git@github.com/"
          # cover 'git://github.com/org/repo.git'
          git config --global url."https://x-access-token:${{ secrets.PAT }}@github.com/".insteadOf "git://github.com/"
          # cover plain https (private repos over https need auth too)
          git config --global url."https://x-access-token:${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"
      - name: install packages
        run: npm clean-install
      - name: Lint code with standard
        run: npm run lint
      - name: Run tests
        run: npm test
